language: ruby
rvm: 2.4.0

env:
  global:
    secure: OjP0mai/8Byodvx0PeYmXdme/XB98/i4ZkxJvwOCfLfFT5ucEwyKB6q2wJJGwKT5wptbH5d92fwkmvtZG4o51yByYs0FewRix/lGOcEwFxmNkdEHGpOHle4f9+W3+rMWTtEMBMReT/Aw5+PuLbdgd//KpwOwUaMVaqTSa5VoDrL/MAN1PmKMp9X6oyRrIopBHi+3dMmHZgzsCBqv2qCKMuYOgIcWTTwcbpwemg1TJcf6QxjT4GrP3tpJG4u/vac6JOD3JhUWZSGahGZuoh1kLbnj3CLNA3Pscp32XVyWLa616F7Mih3FGz8VkQWUvh6ltQuSNO6pkdrmdvrTcjSGgEFO3EU/bCe+qEEiD7pgIv7LMG3MfgR7jlq6Ht6ngLmQQqubsOIbFO8hDDLadriDC10WXdukvHyciy2E1XC4Q59R9900+neNkqwoxkPYB9ICQKq/oka/ec516TOJivBzMiSXtUEMSC8m9b0yIeK28UBeOZmmVwzpaw8pMRiS0Ra08gZcYqweOhmngYidFsDDeg1YleT2/vU8N2jBHuUZ0onGuBvnwEiZwFhfBwQorJmdwtPYg1O5wZOgWDbeeJ2i2WsoNYMzSXEqSXb35Oc5o05o8m/JewmznXt+px1OkHEo/z3weOz9QhA628Mc6KioSuzyF99OSabflGGxr2toZJk=

install:
- bundle install
- curl -O https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/master/Dangerfile

script:
- bundle exec danger

